### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mxsky01** [kutemeikito/android_kernel_xiaomi_ginkgo#11]
ERROR: "ion_alloc_dmabuf" [drivers/media/platform/msm/dvb/demux/mpq-dmx-hw-plugin.ko] undefined!

**Comment by kutemeikito** [comment]
try to git pull, and compile again

**Comment by mxsky01** [comment]
> try to git pull, and compile again

thanks，it‘s succeeded

**Comment by kutemeikito** [comment]
Noice
